In [47]:
import pandas as pd 
data=pd.read_csv("weather.csv");data

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,NW,7.0,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,NNW,2.0,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,ENE,11.0,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,WNW,6.0,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,WNW,31.0,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

In [120]:
data.head()#deafault it takes 1st 5 rows only
data.head(10)

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
5,6.2,16.9,0.0,5.8,8.2,SE,44.0,SE,E,20.0,...,57,1023.8,1021.7,7,5,10.9,14.8,No,0.2,No
6,6.1,18.2,0.2,4.2,8.4,SE,43.0,SE,ESE,19.0,...,47,1024.6,1022.2,4,6,12.4,17.3,No,0.0,No
7,8.3,17.0,0.0,5.6,4.6,E,41.0,SE,E,11.0,...,57,1026.2,1024.2,6,7,12.1,15.5,No,0.0,No
8,8.8,19.5,0.0,4.0,4.1,S,48.0,E,ENE,19.0,...,48,1026.1,1022.7,7,7,14.1,18.9,No,16.2,Yes
9,8.4,22.8,16.2,5.4,7.7,E,31.0,S,ESE,7.0,...,32,1024.1,1020.7,7,1,13.3,21.7,Yes,0.0,No

In [121]:
data.tail() #by default it takes last five rows only

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
361,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,NW,7.0,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,NNW,2.0,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,ENE,11.0,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,WNW,6.0,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,WNW,31.0,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

In [122]:
data.tail(10)

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
356,3.4,15.0,0.8,4.8,11.7,S,70.0,S,S,35.0,...,24,1023.4,1023.1,1,5,8.3,14.3,No,0.0,No
357,3.2,18.0,0.0,7.4,12.2,SSE,48.0,SSE,S,26.0,...,25,1026.6,1022.8,1,2,9.1,16.3,No,0.0,No
358,0.9,20.7,0.0,5.4,8.4,NNW,39.0,SSE,N,2.0,...,29,1023.2,1018.4,3,8,9.4,19.1,No,0.0,No
359,3.3,25.5,0.0,5.2,10.8,N,43.0,N,NNW,4.0,...,16,1018.8,1014.6,0,3,12.0,24.8,No,0.0,No
360,7.9,26.1,0.0,6.8,3.5,NNW,43.0,NaN,WNW,0.0,...,20,1017.6,1014.2,5,8,16.3,25.9,No,0.0,No
361,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,NW,7.0,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,NNW,2.0,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,ENE,11.0,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,WNW,6.0,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,WNW,31.0,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

In [123]:
#for getting columns names
data.columns

Index(['MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation', 'Sunshine',
       'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday', 'RISK_MM', 'RainTomorrow'],
      dtype='object')

In [124]:
#to get total number of columns and rows
data.shape

(366, 22)

In [125]:
# for knowing data types
data.dtypes

MinTemp          float64
MaxTemp          float64
Rainfall         float64
Evaporation      float64
Sunshine         float64
WindGustDir       object
WindGustSpeed    float64
WindDir9am        object
WindDir3pm        object
WindSpeed9am     float64
WindSpeed3pm       int64
Humidity9am        int64
Humidity3pm        int64
Pressure9am      float64
Pressure3pm      float64
Cloud9am           int64
Cloud3pm           int64
Temp9am          float64
Temp3pm          float64
RainToday         object
RISK_MM          float64
RainTomorrow      object
dtype: object

In [126]:
#for getting information of the data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MinTemp        366 non-null    float64
 1   MaxTemp        366 non-null    float64
 2   Rainfall       366 non-null    float64
 3   Evaporation    366 non-null    float64
 4   Sunshine       363 non-null    float64
 5   WindGustDir    363 non-null    object
 6   WindGustSpeed  364 non-null    float64
 7   WindDir9am     335 non-null    object
 8   WindDir3pm     365 non-null    object
 9   WindSpeed9am   359 non-null    float64
 10  WindSpeed3pm   366 non-null    int64
 11  Humidity9am    366 non-null    int64
 12  Humidity3pm    366 non-null    int64
 13  Pressure9am    366 non-null    float64
 14  Pressure3pm    366 non-null    float64
 15  Cloud9am       366 non-null    int64
 16  Cloud3pm       366 non-null    int64
 17  Temp9am        366 non-null    float64
 18  Temp3pm        366 non-null    float64
 19  RainToday      366 non-null    object
 20  RISK_MM        366 non-null    float64
 21  RainTomorrow   366 non-null    object
dtypes: float64(12), int64(5), object(5)
memory usage: 63.0+ KB

In [127]:
# description like basic aggregation of the data
data.describe()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RISK_MM
count,366.000000,366.000000,366.000000,366.000000,363.000000,364.000000,359.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000
mean,7.265574,20.550273,1.428415,4.521858,7.909366,39.840659,9.651811,17.986339,72.035519,44.519126,1019.709016,1016.810383,3.890710,4.024590,12.358470,19.230874,1.428415
std,6.025800,6.690516,4.225800,2.669383,3.481517,13.059807,7.951929,8.856997,13.137058,16.850947,6.686212,6.469422,2.956131,2.666268,5.630832,6.640346,4.225800
min,-5.300000,7.600000,0.000000,0.200000,0.000000,13.000000,0.000000,0.000000,36.000000,13.000000,996.500000,996.800000,0.000000,0.000000,0.100000,5.100000,0.000000
25%,2.300000,15.025000,0.000000,2.200000,5.950000,31.000000,6.000000,11.000000,64.000000,32.250000,1015.350000,1012.800000,1.000000,1.000000,7.625000,14.150000,0.000000
50%,7.450000,19.650000,0.000000,4.200000,8.600000,39.000000,7.000000,17.000000,72.000000,43.000000,1020.150000,1017.400000,3.500000,4.000000,12.550000,18.550000,0.000000
75%,12.500000,25.500000,0.200000,6.400000,10.500000,46.000000,13.000000,24.000000,81.000000,55.000000,1024.475000,1021.475000,7.000000,7.000000,17.000000,24.000000,0.200000
max,20.900000,35.800000,39.800000,13.800000,13.600000,98.000000,41.000000,52.000000,99.000000,96.000000,1035.700000,1033.200000,8.000000,8.000000,24.700000,34.500000,39.800000

In [128]:
#some calculations
print("maximum:",data.max())
print("minimum:",data.min())
print("mean:",data.mean())
print("median:",data.median())
print("variance:",data.var())
print("standard deviation:",data.std())
print("skewness:",data.skew())
print("kurtosis:",data.kurt())
print("count:",data.count())

maximum: MinTemp            20.9
MaxTemp            35.8
Rainfall           39.8
Evaporation        13.8
Sunshine           13.6
WindGustSpeed      98.0
WindSpeed9am       41.0
WindSpeed3pm         52
Humidity9am          99
Humidity3pm          96
Pressure9am      1035.7
Pressure3pm      1033.2
Cloud9am              8
Cloud3pm              8
Temp9am            24.7
Temp3pm            34.5
RainToday           Yes
RISK_MM            39.8
RainTomorrow        Yes
dtype: object
minimum: MinTemp           -5.3
MaxTemp            7.6
Rainfall           0.0
Evaporation        0.2
Sunshine           0.0
WindGustSpeed     13.0
WindSpeed9am       0.0
WindSpeed3pm         0
Humidity9am         36
Humidity3pm         13
Pressure9am      996.5
Pressure3pm      996.8
Cloud9am             0
Cloud3pm             0
Temp9am            0.1
Temp3pm            5.1
RainToday           No
RISK_MM            0.0
RainTomorrow        No
dtype: object
mean: MinTemp             7.265574
MaxTemp            20.550273
Rainfall            1.428415
Evaporation         4.521858
Sunshine            7.909366
WindGustSpeed      39.840659
WindSpeed9am        9.651811
WindSpeed3pm       17.986339
Humidity9am        72.035519
Humidity3pm        44.519126
Pressure9am      1019.709016
Pressure3pm      1016.810383
Cloud9am            3.890710
Cloud3pm            4.024590
Temp9am            12.358470
Temp3pm            19.230874
RISK_MM             1.428415
dtype: float64
median: MinTemp             7.45
MaxTemp            19.65
Rainfall            0.00
Evaporation         4.20
Sunshine            8.60
WindGustSpeed      39.00
WindSpeed9am        7.00
WindSpeed3pm       17.00
Humidity9am        72.00
Humidity3pm        43.00
Pressure9am      1020.15
Pressure3pm      1017.40
Cloud9am            3.50
Cloud3pm            4.00
Temp9am            12.55
Temp3pm            18.55
RISK_MM             0.00
dtype: float64
variance: MinTemp           36.310264
MaxTemp           44.763000
Rainfall          17.857382
Evaporation        7.125603
Sunshine          12.120962
WindGustSpeed    170.558563
WindSpeed9am      63.233174
WindSpeed3pm      78.446388
Humidity9am      172.582297
Humidity3pm      283.954428
Pressure9am       44.705425
Pressure3pm       41.853426
Cloud9am           8.738708
Cloud3pm           7.108983
Temp9am           31.706271
Temp3pm           44.094195
RISK_MM           17.857382
dtype: float64
standard deviation: MinTemp           6.025800
MaxTemp           6.690516
Rainfall          4.225800
Evaporation       2.669383
Sunshine          3.481517
WindGustSpeed    13.059807
WindSpeed9am      7.951929
WindSpeed3pm      8.856997
Humidity9am      13.137058
Humidity3pm      16.850947
Pressure9am       6.686212
Pressure3pm       6.469422
Cloud9am          2.956131
Cloud3pm          2.666268
Temp9am           5.630832
Temp3pm           6.640346
RISK_MM           4.225800
dtype: float64
skewness: MinTemp         -0.003811
MaxTemp          0.350377
Rainfall         4.590163
Evaporation      0.663658
Sunshine        -0.729472
WindGustSpeed    0.843041
WindSpeed9am     1.371612
WindSpeed3pm     0.596150
Humidity9am     -0.141457
Humidity3pm      0.594731
Pressure9am     -0.348591
Pressure3pm     -0.295247
Cloud9am         0.080433
Cloud3pm         0.072898
Temp9am         -0.021783
Temp3pm          0.303510
RISK_MM          4.590163
dtype: float64
kurtosis: MinTemp          -1.114221
MaxTemp          -0.745130
Rainfall         26.780950
Evaporation      -0.179540
Sunshine         -0.242367
WindGustSpeed     1.538286
WindSpeed9am      1.538881
WindSpeed3pm      0.233391
Humidity9am      -0.176680
Humidity3pm       0.045045
Pressure9am      -0.043636
Pressure3pm      -0.003030
Cloud9am         -1.716841
Cloud3pm         -1.628532
Temp9am          -0.956998
Temp3pm          -0.666524
RISK_MM          26.780950
dtype: float64
count: MinTemp          366
MaxTemp          366
Rainfall         366
Evaporation      366
Sunshine         363
WindGustDir      363
WindGustSpeed    364
WindDir9am       335
WindDir3pm       365
WindSpeed9am     359
WindSpeed3pm     366
Humidity9am      366
Humidity3pm      366
Pressure9am      366
Pressure3pm      366
Cloud9am         366
Cloud3pm         366
Temp9am          366
Temp3pm          366
RainToday        366
RISK_MM          366
RainTomorrow     366
dtype: int64

C:\Users\LOKESH~1\AppData\Local\Temp/ipykernel_23992/4104913621.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print("maximum:",data.max())
C:\Users\LOKESH~1\AppData\Local\Temp/ipykernel_23992/4104913621.py:3: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print("minimum:",data.min())
C:\Users\LOKESH~1\AppData\Local\Temp/ipykernel_23992/4104913621.py:4: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print("mean:",data.mean())
C:\Users\LOKESH~1\AppData\Local\Temp/ipykernel_23992/4104913621.py:5: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print("median:",data.median())
C:\Users\LOKESH~1\AppData\Local\Temp/ipykernel_23992/4104913621.py:6: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print("variance:",data.var())
C:\Users\LOKESH~1\AppData\Local\Temp/ipykernel_23992/4104913621.py:7: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print("standard deviation:",data.std())
C:\Users\LOKESH~1\AppData\Local\Temp/ipykernel_23992/4104913621.py:8: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print("skewness:",data.skew())
C:\Users\LOKESH~1\AppData\Local\Temp/ipykernel_23992/4104913621.py:9: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print("kurtosis:",data.kurt())

In [129]:
print(data['Rainfall'].count())
print(data['Rainfall'].mean())
print(data['Rainfall'].var())

366
1.4284153005464482
17.857382139381833

In [130]:
#to get frequency of the values or records
print(data['Rainfall'].value_counts())

0.0     263
0.2      17
0.6       6
0.8       5
0.4       5
1.0       4
6.6       3
1.8       3
5.2       3
4.8       3
2.0       3
4.0       3
3.4       3
1.2       3
3.6       2
3.8       2
1.4       2
3.0       2
6.4       2
11.0      2
17.4      2
1.6       2
16.2      2
2.6       1
8.2       1
7.2       1
7.6       1
19.2      1
6.2       1
9.8       1
7.4       1
16.8      1
19.8      1
18.8      1
10.4      1
4.4       1
9.0       1
2.2       1
12.2      1
14.4      1
5.4       1
4.2       1
22.6      1
25.8      1
2.8       1
39.8      1
13.2      1
Name: Rainfall, dtype: int64

In [131]:
data.value_counts

<bound method DataFrame.value_counts of      MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0        8.0     24.3       0.0          3.4       6.3          NW
1       14.0     26.9       3.6          4.4       9.7         ENE
2       13.7     23.4       3.6          5.8       3.3          NW
3       13.3     15.5      39.8          7.2       9.1          NW
4        7.6     16.1       2.8          5.6      10.6         SSE
..       ...      ...       ...          ...       ...         ...
361      9.0     30.7       0.0          7.6      12.1         NNW
362      7.1     28.4       0.0         11.6      12.7           N
363     12.5     19.9       0.0          8.4       5.3         ESE
364     12.5     26.9       0.0          5.0       7.1          NW
365     12.3     30.2       0.0          6.0      12.6          NW

     WindGustSpeed WindDir9am WindDir3pm  WindSpeed9am  ...  Humidity3pm  \
0             30.0         SW         NW           6.0  ...           29
1             39.0          E          W           4.0  ...           36
2             85.0          N        NNE           6.0  ...           69
3             54.0        WNW          W          30.0  ...           56
4             50.0        SSE        ESE          20.0  ...           49
..             ...        ...        ...           ...  ...          ...
361           76.0        SSE         NW           7.0  ...           15
362           48.0        NNW        NNW           2.0  ...           22
363           43.0        ENE        ENE          11.0  ...           47
364           46.0        SSW        WNW           6.0  ...           39
365           78.0         NW        WNW          31.0  ...           13

     Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  \
0         1019.7       1015.0         7         7     14.4     23.6
1         1012.4       1008.4         5         3     17.5     25.7
2         1009.5       1007.2         8         7     15.4     20.2
3         1005.5       1007.0         2         7     13.5     14.1
4         1018.3       1018.5         7         7     11.1     15.4
..           ...          ...       ...       ...      ...      ...
361       1016.1       1010.8         1         3     20.4     30.0
362       1020.0       1016.9         0         1     17.2     28.2
363       1024.0       1022.8         3         2     14.5     18.3
364       1021.0       1016.2         6         7     15.8     25.9
365       1009.6       1009.2         1         1     23.8     28.6

     RainToday  RISK_MM RainTomorrow
0           No      3.6          Yes
1          Yes      3.6          Yes
2          Yes     39.8          Yes
3          Yes      2.8          Yes
4          Yes      0.0           No
..         ...      ...          ...
361         No      0.0           No
362         No      0.0           No
363         No      0.0           No
364         No      0.0           No
365         No      0.0           No

[366 rows x 22 columns]>

In [134]:
# to get columns for our convinience
data[['Rainfall','RainTomorrow']]

     Rainfall RainTomorrow
0         0.0          Yes
1         3.6          Yes
2         3.6          Yes
3        39.8          Yes
4         2.8           No
..        ...          ...
361       0.0           No
362       0.0           No
363       0.0           No
364       0.0           No
365       0.0           No

[366 rows x 2 columns]

In [7]:
data[['MinTemp','MaxTemp','Rainfall','Evaporation','Sunshine']]

     MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine
0        8.0     24.3       0.0          3.4       6.3
1       14.0     26.9       3.6          4.4       9.7
2       13.7     23.4       3.6          5.8       3.3
3       13.3     15.5      39.8          7.2       9.1
4        7.6     16.1       2.8          5.6      10.6
..       ...      ...       ...          ...       ...
361      9.0     30.7       0.0          7.6      12.1
362      7.1     28.4       0.0         11.6      12.7
363     12.5     19.9       0.0          8.4       5.3
364     12.5     26.9       0.0          5.0       7.1
365     12.3     30.2       0.0          6.0      12.6

[366 rows x 5 columns]

In [11]:
data['Rainfall'][data['RainToday']=='Yes']#which gives Rainfall recoreds where RainToday is 'yes'

1       3.6
2       3.6
3      39.8
4       2.8
9      16.2
       ...
327    17.4
338     7.6
339     3.0
341     8.2
348    13.2
Name: Rainfall, Length: 66, dtype: float64

In [21]:
data[data['RainToday']=='No']# displaying records where rain today is 'no'

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
5,6.2,16.9,0.0,5.8,8.2,SE,44.0,SE,E,20.0,...,57,1023.8,1021.7,7,5,10.9,14.8,No,0.2,No
6,6.1,18.2,0.2,4.2,8.4,SE,43.0,SE,ESE,19.0,...,47,1024.6,1022.2,4,6,12.4,17.3,No,0.0,No
7,8.3,17.0,0.0,5.6,4.6,E,41.0,SE,E,11.0,...,57,1026.2,1024.2,6,7,12.1,15.5,No,0.0,No
8,8.8,19.5,0.0,4.0,4.1,S,48.0,E,ENE,19.0,...,48,1026.1,1022.7,7,7,14.1,18.9,No,16.2,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,NW,7.0,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,NNW,2.0,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,ENE,11.0,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,WNW,6.0,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,WNW,31.0,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

In [28]:
data[data['Rainfall']>25]  #or data[data.Rainfall>30]

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
22,12.8,18.5,25.8,2.8,0.6,ESE,28.0,S,SE,13.0,...,79,1014.0,1014.9,8,8,14.0,16.8,Yes,0.4,No

In [25]:
data[data.Rainfall<10]

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
5,6.2,16.9,0.0,5.8,8.2,SE,44.0,SE,E,20.0,...,57,1023.8,1021.7,7,5,10.9,14.8,No,0.2,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,NW,7.0,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,NNW,2.0,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,ENE,11.0,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,WNW,6.0,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,WNW,31.0,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

In [26]:
#for getting data where rainfall is maximum
data[data['Rainfall']==data['Rainfall'].max()]

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes

In [33]:
data[['Rainfall','Sunshine']][data['RainToday']=='No']

     Rainfall  Sunshine
0         0.0       6.3
5         0.0       8.2
6         0.2       8.4
7         0.0       4.6
8         0.0       4.1
..        ...       ...
361       0.0      12.1
362       0.0      12.7
363       0.0       5.3
364       0.0       7.1
365       0.0      12.6

[300 rows x 2 columns]

In [138]:
#slicy and dicy of data
data.iloc[:,:]#returns all the records -->indexlocator(from n row:to m row,from n col : to m column)

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,NW,7.0,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,NNW,2.0,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,ENE,11.0,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,WNW,6.0,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,WNW,31.0,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

In [142]:
data.iloc[0:5,0:10]

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0

In [3]:
data.iloc[1:3,]# or data[1:3]

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes

In [6]:
data[1:5]# which gives row 1 to 4

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No

In [17]:
#gives the inex of the data
data.index

RangeIndex(start=0, stop=366, step=1)

In [18]:
data.set_index('MinTemp')      # for setting column as a index for the data but its not changed in original data so we use inplace function

,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
MinTemp,,,,,,,,,,,,,,,,,,,,,
8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,20,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,17,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,6,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,24,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,28,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,NW,7.0,50,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,NNW,2.0,19,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,ENE,11.0,9,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,WNW,6.0,28,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,WNW,31.0,35,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

In [49]:
data.set_index('MinTemp',inplace=True)

In [25]:
data.loc[8.0] # which shows the value corresponding to the MinTemp 8.0

MaxTemp            24.3
Rainfall            0.0
Evaporation         3.4
Sunshine            6.3
WindGustDir          NW
WindGustSpeed      30.0
WindDir9am           SW
WindDir3pm           NW
WindSpeed9am        6.0
WindSpeed3pm         20
Humidity9am          68
Humidity3pm          29
Pressure9am      1019.7
Pressure3pm      1015.0
Cloud9am              7
Cloud3pm              7
Temp9am            14.4
Temp3pm            23.6
RainToday            No
RISK_MM             3.6
RainTomorrow        Yes
Name: 8.0, dtype: object

In [62]:
data.set_index('WindGustDir',inplace=True)

In [63]:
data.loc['NW'] #which is similar to data[data.WindGustDir=='NW']

,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
WindGustDir,,,,,,,,,,,,,,,,,,,,
NW,24.3,0.0,3.4,6.3,30.0,SW,NW,6.0,20,68,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
NW,23.4,3.6,5.8,3.3,85.0,N,NNE,6.0,6,82,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
NW,15.5,39.8,7.2,9.1,54.0,WNW,W,30.0,24,62,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
NW,30.9,0.0,6.2,12.4,44.0,WNW,W,7.0,20,67,20,1017.3,1013.1,1,4,19.7,30.7,No,0.0,No
NW,31.2,0.0,8.8,13.1,41.0,S,W,6.0,20,45,16,1018.2,1013.7,0,1,18.7,30.4,No,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
NW,24.7,0.0,5.4,8.6,43.0,N,NW,4.0,20,80,31,1025.7,1022.2,1,7,12.7,23.7,No,0.0,No
NW,28.5,0.0,5.8,9.8,46.0,W,NW,2.0,26,66,30,1024.1,1019.8,1,6,16.8,27.4,No,0.2,No
NW,27.4,0.2,7.6,12.1,52.0,SE,NW,6.0,31,60,20,1021.4,1017.5,1,1,16.4,26.3,No,0.0,No
NW,26.9,0.0,5.0,7.1,46.0,SSW,WNW,6.0,28,69,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
NW,30.2,0.0,6.0,12.6,78.0,NW,WNW,31.0,35,43,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

In [53]:
data[data['WindGustDir']=='NW']   #shows error since we change the data as WindGustDir as index

KeyError: 'WindGustDir'

In [55]:
data[data['WindDir3pm']=='NW']  #since wi did not set windDir3pm as index for data

,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
WindGustDir,,,,,,,,,,,,,,,,,,,,
NW,24.3,0.0,3.4,6.3,30.0,SW,NW,6.0,20,68,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
N,25.2,0.0,4.2,11.9,30.0,SE,NW,6.0,9,74,34,1024.4,1021.1,1,2,14.6,24.0,No,0.2,No
E,27.3,0.2,7.2,12.5,41.0,E,NW,2.0,15,54,35,1023.8,1019.9,0,3,16.8,26.0,No,0.0,No
WNW,27.9,0.0,7.2,13.0,30.0,S,NW,6.0,7,62,29,1022.0,1017.1,0,1,17.0,27.1,No,0.0,No
WNW,33.4,0.0,8.8,9.5,59.0,N,NW,2.0,31,60,26,1012.4,1006.5,1,5,22.2,32.8,No,0.4,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
NW,21.0,0.0,4.2,12.2,28.0,SW,NW,2.0,9,73,30,1025.7,1022.3,1,1,9.6,19.2,No,0.0,No
NW,24.7,0.0,5.4,8.6,43.0,N,NW,4.0,20,80,31,1025.7,1022.2,1,7,12.7,23.7,No,0.0,No
NW,28.5,0.0,5.8,9.8,46.0,W,NW,2.0,26,66,30,1024.1,1019.8,1,6,16.8,27.4,No,0.2,No
NW,27.4,0.2,7.6,12.1,52.0,SE,NW,6.0,31,60,20,1021.4,1017.5,1,1,16.4,26.3,No,0.0,No
NNW,30.7,0.0,7.6,12.1,76.0,SSE,NW,7.0,50,38,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No

In [64]:
data.reset_index(inplace=True) #retrives the original data that means delete the changes that takes place in index of the data,if we run data.loc['NW'] its shows error
data

,WindGustDir,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,NW,24.3,0.0,3.4,6.3,30.0,SW,NW,6.0,20,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,ENE,26.9,3.6,4.4,9.7,39.0,E,W,4.0,17,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,NW,23.4,3.6,5.8,3.3,85.0,N,NNE,6.0,6,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,NW,15.5,39.8,7.2,9.1,54.0,WNW,W,30.0,24,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,SSE,16.1,2.8,5.6,10.6,50.0,SSE,ESE,20.0,28,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,NNW,30.7,0.0,7.6,12.1,76.0,SSE,NW,7.0,50,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,N,28.4,0.0,11.6,12.7,48.0,NNW,NNW,2.0,19,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,ESE,19.9,0.0,8.4,5.3,43.0,ENE,ENE,11.0,9,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,NW,26.9,0.0,5.0,7.1,46.0,SSW,WNW,6.0,28,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,NW,30.2,0.0,6.0,12.6,78.0,NW,WNW,31.0,35,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No